/*
 * generated by Xtext 2.9.2
 */
package org.myasm.assembly.compiler.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class MyAsmIdeaModule extends AbstractMyAsmIdeaModule {
}
