/*
 * generated by Xtext 2.9.2
 */
package org.myasm.assembly.compiler.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class MyAsmIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new MyAsmStandaloneSetupIdea().createInjector
	}

}
