/*
 * generated by Xtext 2.9.2
 */
package org.myasm.assembly.compiler.idea.lang


class MyAsmFileType extends AbstractMyAsmFileType {
	public static final MyAsmFileType INSTANCE = new MyAsmFileType()
	
	new() {
		super(MyAsmLanguage.INSTANCE)
	}
}
